version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 18

    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y unzip git libpq-dev libzip-dev
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - composer --version

  pre_build:
    commands:
      - echo Running composer install...
      - composer install --no-dev --optimize-autoloader
      - echo Running npm install...
      - npm install
      - npm run build || true

artifacts:
  files:
    - '**/*'
