version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y unzip git libpq-dev libzip-dev

      # Install composer (once)
      - curl -sS https://getcomposer.org/installer -o composer-setup.php
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - composer --version

  pre_build:
    commands:
      - echo Running composer install...
      - composer install --no-dev --optimize-autoloader
      - npm install
      - npm run build

artifacts:
  files:
    - '**/*'
  name: build-artifact.zip
proxy:
  upload-artifacts: yes