version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 20   # 🔥 CHANGE THIS
    commands:
      - echo Installing Composer...
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer

  pre_build:
    commands:
      - echo Installing PHP dependencies...
      - composer install --no-dev --optimize-autoloader

      - echo Installing Node dependencies...
      - npm install

  build:
    commands:
      - echo Building frontend assets...
      - npm run build
      - php artisan config:cache
      - php artisan route:cache

artifacts:
  files:
    - '**/*'
